### ISSUE TITLE
removing shotwell should remove shotwell-common if present

### ISSUE THREAD

**Issue by chrstphrchvz** [ubuntu-mate/software-boutique#7]
The PPA does not use a shotwell-common package (the PPA shotwell package is specified to replace shotwell-common). However if shotwell is currently installed from Ubuntu packages rather than the PPA, requesting its removal from the software boutique leaves behind shotwell-common. 

I'm not sure where the shotwell listing currently lives after the split from ubuntu-mate-welcome…

**Comment by flexiondotorg** [comment]
https://github.com/ubuntu-mate/ubuntu-mate-welcome/commit/ad2d91af8d6cc19d86663aabd529c8c04f9cdd19
