### ISSUE TITLE
Installing spotify no longer works.

### ISSUE THREAD

**Issue by tylnesh** [ubuntu-mate/software-boutique#8]
Seems like the name of the package is broken in the spotify installer in Boutique. Should be corrected to the snap package spotify

**Comment by vickael** [comment]
Software boutique does not import key repository Spotify.

**Comment by flexiondotorg** [comment]
This is fixed via https://github.com/ubuntu-mate/ubuntu-mate-welcome/commit/cc5728086e031a9ab88b1f25002704bfa8caac8d
